//Entity
//GET /api/orders?pageNumber=1&pageSize=10
public class Order
{
    public int Id { get; set; }

    public string ProductName { get; set; }

    public decimal Price { get; set; }
}



[HttpGet]
public async Task<IActionResult> GetOrders(int pageNumber = 1, int pageSize = 10)
{
    var orders = await _context.Orders
        .OrderBy(o => o.Id)
        .Skip((pageNumber - 1) * pageSize)
        .Take(pageSize)
        .ToListAsync();

    return Ok(orders);
}

//EF Core generated by SQL
SELECT*
FROM Orders
ORDER BY Id
OFFSET 10 ROWS
FETCH NEXT 10 ROWS ONLY;
//this is another way 
public async Task<IActionResult> GetOrders(
    [FromQuery] PaginationFilter filter)
{
}